camel.main.name=peppol-bis-billing-icp
camel.main.routesIncludePattern=classpath:routes/peppol-*.camel.yaml

sample.http.host=0.0.0.0
sample.http.port=8080
sample.ic.location=http://127.0.0.1:4943/
sample.ic.canister=